version: "3"

services: 
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: brbatel-web
    volumes: 
      - .:/var/www/html
    ports: 
      - 127.0.0.1:${PORT}:3000
    environment: 
      CHOKIDAR_USEPOLLING: "true"
      API_BASE_URL: ${API_BASE_URL}
      PORT: ${PORT}